services:

  servidor:
    build: ./cliente-servidor-csharp/servidor
    container_name: servidor-csharp
    ports:
      - "5000:5000"

  cliente:
    build: ./cliente-servidor-csharp/cliente
    depends_on:
      - servidor
    deploy:
      replicas: 10
